-- PostgreSQL equivalent of migrations/sqlite/001_init.sql (same version,
-- same tables, columns and defaults). Differences are dialect only:
--   * INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   * user_id foreign keys               -> BIGINT, matching users.id
--   * DEFAULT (datetime('now'))          -> the same "YYYY-MM-DD HH:MM:SS" UTC
--     text, produced with to_char
--   * columns the API sorts or range-compares as text use COLLATE "C", so
--     ordering matches SQLite's byte-wise BINARY collation
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     TEXT NOT NULL UNIQUE,
    email        TEXT,
    display_name TEXT,
    pw_hash      TEXT,
    role         TEXT NOT NULL DEFAULT 'viewer',
    created_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    updated_at   TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE sessions (
    token       TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    csrf_token  TEXT NOT NULL,
    expires_at  TEXT COLLATE "C" NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE oidc_links (
    user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    issuer   TEXT NOT NULL,
    subject  TEXT NOT NULL,
    email    TEXT,
    PRIMARY KEY (issuer, subject)
);

CREATE TABLE audit_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts         TEXT COLLATE "C" NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    actor      TEXT NOT NULL,
    method     TEXT NOT NULL,
    path       TEXT NOT NULL,
    target     TEXT,
    status     INTEGER NOT NULL,
    ip         TEXT
);

CREATE INDEX idx_audit_ts ON audit_events(ts DESC);

CREATE TABLE api_tokens (
    token       TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
    last_used   TEXT
);

CREATE INDEX idx_api_tokens_user ON api_tokens(user_id);
